name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      IMAGE_ID: docker.pkg.github.com/${{ github.repository }}/application:${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        # check docker/build.sh for a sample
        run: ./build.sh $IMAGE_ID

      - name: Log into registry
        if: ${{ github.event_name == 'push' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: ${{ github.event_name == 'push' }}
        run: docker push $IMAGE_ID
